{
 "title": "Holistic Webshop Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(flask_http_request_duration_seconds_sum, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=\"$service\"}[1m]))/sum(rate(node_cpu_seconds_total{job=\"node\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Rate and Error Count of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{service=\"$service\"}[1m]))",
     "legendFormat": "Return Status {{status}}"
    }
   ]
  },
  {
   "title": "Latency of $service by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(traces_spanmetrics_latency_sum{service_name=\"$service\"}[$__interval])/rate(traces_spanmetrics_latency_count{service_name=\"$service\"}[$__interval]))",
     "legendFormat": "{{service_name}} {{ operation }}"
    }
   ]
  },
  {
   "title": "Average Latency of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{service=~\"$service\"}[10m])) * 1 / sum(rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[10m]))",
     "legendFormat": "Average [10m]"
    }
   ]
  },
  {
   "title": "5m Average Number of Web Shop Logs by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (compose_service) (count_over_time({compose_project=\"web-shop-o11y-demo\"}[5m]))",
     "legendFormat": "{{compose_service}}"
    }
   ]
  },
  {
   "title": "Web Shop Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{compose_project=\"web-shop-o11y-demo\"}"
    }
   ]
  }
 ]
}