version: '3'

networks:
  web-shop:
    driver: bridge

services:

  grafana:
    image: grafana/grafana:9.4.7
    volumes:
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
      - "./grafana/conf:/etc/grafana/"
    ports:
      - "3000:3000"
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "publicDashboards ngalert accesscontrol panelTitleSearch tempoSearch tempoApmTable traceToMetrics recordedQueries traceqlEditor flameGraph topnav"
      GF_INSTALL_PLUGINS: "grafana-k6-app,grafana-polystat-panel"
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  mimir:
    image: grafana/mimir:2.5.0
    ports:
     - "9009:9009"
    volumes:
     - "./mimir/demo.yaml:/etc/mimir/demo.yaml"
    command:
      - '--config.file=/etc/mimir/demo.yaml'
    networks:
     - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  loki:
    image: grafana/loki:2.7.2
    ports:
      - "3100:3100"
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  tempo:
    image: grafana/tempo:2.0.0
    ports:
      - "3200"
      - "4317"
      - "55680"
      - "55681"
      - "14250"
    command: [ "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  agent:
    image: grafana/agent:v0.31.0
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent/agent.yaml
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    ports:
      - "80"
      - "6832"
      - "55679"
      - "4317:4317"
      - "1234:1234"
      - "12347:12347"
    volumes:
      - "./agent/config.yaml:/etc/agent/agent.yaml"
    networks:
      - web-shop
    environment:
      APP_ENDPOINT: http://${PUBLIC_APP_URL}:3389
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  web-shop:
    image: "condla/web-shop:2.1-grafana-cloud"
      #build: "./web-shop"
    ports:
      - "3389:3389"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4317"
      APP_AGENT_RECEIVER_ENDPOINT: "http://${PUBLIC_APP_URL}:12347"
    depends_on:
      - "shopping-cart"
    networks:
      - web-shop
    restart: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  shopping-cart:
    image: "condla/shopping-cart:1.4"
    #build: "./shopping-cart"
    ports:
      - "5555:5555"
    environment:
      SQLALCHEMY_DATABASE_URI: mariadb+mariadbconnector://root:myrootpassword@mariadb:3306/webshopdb
      OTEL_EXPORTER_OTLP_ENDPOINT: http://agent:4317
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  products:
    image: "condla/products:otel-1.6"
      #build: "./products"
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      OTEL_METRICS_EXPORTER: "none"
      OTEL_EXPORTER: "otlp_span"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=products,team.name=backend,environment=production"
      OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED: "true"
      JAVA_OPTS: "-javaagent:/opentelemetry-javaagent.jar -javaagent:/jmx_prometheus_javaagent.jar=8081:/httpserver.yml"
    networks:
      - web-shop
    depends_on:
      - "shopping-cart"
      - "broker"
    security_opt:
      - seccomp:phlare/seccomp.json
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: myrootpassword
      MARIADB_DATABASE: webshopdb
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)
    healthcheck:
      test: mariadb-admin ping -h 127.0.01 -uroot -pmyrootpassword
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  broker:
    image: confluentinc/cp-server:7.0.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CREATE_TOPICS: audit:1:1,networkevents:1:1,webserverlogs:1:1,dbcommits:1:1,machine1:1:1,machine2:1:1
      #KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  squid:
    image: ubuntu/squid
    ports:
      - "3128:3128"
    restart: unless-stopped
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
    environment:
      TZ: UTC
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100
    networks:
      - web-shop

#  blackbox_exporter:
#    image: prom/blackbox-exporter:master
#    volumes:
#        - ./blackbox_exporter:/config
#    command: --config.file=/config/blackbox.yml
#    ports:
#      - 9115:9115


