{
 "title": "Holistic Webshop Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } },
   { "name": "app", "label": "App", "query": "web-shop-frontend" }
  ]
 },
 "panels": [
  { "title": "Front End Health Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\",kind=\"exception\"} [$__range])) by (app)"
    }
   ]
  },
  {
   "title": "TTFB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \"ttfb\" | logfmt | unwrap ttfb [$__range]) by (app)",
     "legendFormat": "TTFB"
    }
   ]
  },
  {
   "title": "FCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" fcp=\" | logfmt | unwrap fcp [$__range]) by (app)",
     "legendFormat": "FCP"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \"cls\" | logfmt | unwrap cls [$__range]) by (app)",
     "legendFormat": "CLS"
    }
   ]
  },
  {
   "title": "LCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" lcp=\" | logfmt | unwrap lcp [$__range]) by (app)",
     "legendFormat": "LCP"
    }
   ]
  },
  {
   "title": "FID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" fid=\" | logfmt | unwrap fid [$__range]) by (app)",
     "legendFormat": "FID"
    }
   ]
  },
  {
   "title": "Endpoint Heath + 4 Golden Signals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Error Percentage of Failing Endpoints",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_target) (rate(traces_spanmetrics_latency_count{status_code=\"STATUS_CODE_ERROR\", http_target!=\"*\", http_target=~\".+\", service=~\"$service\"}[1m])) / sum by (http_target) (rate(traces_spanmetrics_latency_count{ http_target!=\"*\", http_target=~\".+\", service=~\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "Service Map",
   "type": "nodeGraph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Rate and Error Count of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[1m]))",
     "legendFormat": "Return Status {{status}}"
    },
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{service=~\"$service\"}[1m]))",
     "legendFormat": "Return Status {{status}}"
    },
    {
     "expr": "sum by (code) (rate(gin_requests_total{}[1m]))",
     "legendFormat": "Return Status {{code}}"
    }
   ]
  },
  {
   "title": "CPU Usage of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=~\"$service\"}[1m]))/sum(rate(node_cpu_seconds_total{job=\"node\"}[1m]))",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(rate(process_cpu_usage{service=~\"$service\"}[1m]))/sum(rate(node_cpu_seconds_total{job=\"node\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Percentage Per Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_name) (rate(traces_spanmetrics_latency_count{status_code != \"STATUS_CODE_UNSET\", service=~\"$service\"}[1m]))/sum by (service_name) (rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m]))",
     "legendFormat": "{{ service_name }}"
    }
   ]
  },
  {
   "title": "Total Spans Error Percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(traces_spanmetrics_latency_count{status_code != \"STATUS_CODE_UNSET\"}[1m]))/sum (rate(traces_spanmetrics_latency_count{}[1m]))"
    }
   ]
  },
  {
   "title": "Status Code non-2xx Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (svc) (count_over_time({traces=\"span\"} | logfmt | svc=~\"$service\" | http_status_code =~ \"...\" | http_status_code!~\"2..\" [1m])) / sum by (svc) (count_over_time({traces=\"span\"} | logfmt | svc=~\"$service\" | http_status_code=~\"...\" [1m]))",
     "legendFormat": "{{ svc }}"
    }
   ]
  },
  {
   "title": "Average Latency of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{service=~\"$service\"}[10m])) * 1 / sum(rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[10m]))",
     "legendFormat": "Average [10m]"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=~\"$service\"}[10m])) * 1 / sum(rate(http_server_requests_seconds_count{service=~\"$service\"}[10m]))",
     "legendFormat": "Average [10m]"
    }
   ]
  },
  {
   "title": "Endpoints of $service with Highest Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,sum by (span_name) (rate(traces_spanmetrics_latency_sum{service=~\"$service\"}[1m]))/sum by (span_name)(rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Latency of $service by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(traces_spanmetrics_latency_sum{service=~\"$service\"}[1m]))/sum by (span_name)(rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m]))",
     "legendFormat": "{{service_name}} {{ operation }}"
    }
   ]
  },
  {
   "title": "5m Average Number of Web Shop Logs by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (compose_service) (count_over_time({compose_project=\"web-shop-o11y-demo\"}[5m]))",
     "legendFormat": "{{compose_service}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Web Shop Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{compose_project=\"web-shop-o11y-demo\"}"
    }
   ]
  },
  {
   "title": "Span Count per 5 Minutes per Team",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (team_name) (sum_over_time(traces_spanmetrics_latency_count{}[5m]))",
     "legendFormat": "{{ team_name }} team"
    }
   ]
  }
 ]
}