{
 "title": "Holistic Webshop Observability",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } },
   { "name": "app", "label": "App", "query": "web-shop-frontend" },
   { "name": "order_id", "label": "Order ID" }
  ]
 },
 "panels": [
  {
   "title": "Instructions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "## Holistic Observability\n\nHolistic Observability covers not only metrics from infrastructure and applications, it covers metrics, logs, traces, profiles and any other telemetry or data that is important for you and that you want to correlate.\n\n## About this Web Shop Demo\n\n This is an example dashboard on how to correlate business data (MariaDB, MongoDB, PostgreSQL,...) with telemetry from infrastructure and applications.\n Each order in the web shop has a specific order ID. There's a free text field on the top of this dashboard, so you can copy/paste any order id from e.g. customer incidents, but you can also browse different orders by clicking on the order id of one of the top orders in the chosen time frame. Choosing a valid order id will automatically populate a few other panels as well as filter the logs down to those with the specific order id."
     }
    }
   ]
  },
  {
   "title": "Business Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Order Size",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT uuid, avg(amount) FROM\n(SELECT orders.cart_id, orders.order_uuid as uuid, orders.created_date, SUM(price*quantity) AS amount from order_table AS orders\nJOIN cart ON cart.id = orders.cart_id\nJOIN cart_item ON cart.id = cart_item.cart_id\nJOIN product ON cart_item.product_id = product.id\nWHERE  $__timeFilter(orders.created_date)\nGROUP BY (orders.order_uuid)) AS t"
      }
     ]
    },
    {
     "title": "Average Spend by Customer",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT avg(amount) FROM\n  (\n    SELECT orders.cart_id, cart.customer_id as cust_id, orders.created_date, SUM(price*quantity) AS amount from order_table AS orders\n      JOIN cart ON cart.id = orders.cart_id\n      JOIN cart_item ON cart.id = cart_item.cart_id\n      JOIN product ON cart_item.product_id = product.id\n      WHERE  $__timeFilter(orders.created_date)\n      GROUP BY (cart.customer_id)\n  ) AS t"
      }
     ]
    },
    {
     "title": "Most popular item",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT product.name, sum(cart_item.quantity) as amount FROM cart_item \n  JOIN product\n  ON cart_item.product_id = product.id\n  JOIN cart ON cart_item.cart_id = cart.id\n  JOIN customer ON cart.customer_id = customer.id\n  WHERE $__timeFilter(cart_item.created_date) \n  GROUP BY product.name ORDER BY amount DESC LIMIT 1;"
      }
     ]
    },
    {
     "title": "Top 5 Current Biggest Shopping Carts (Before Checkout)",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "rawSql": "SELECT customer.name, sum(cart_item.quantity * product.price)\n  FROM cart_item \n  JOIN product\n  ON cart_item.product_id = product.id\n  JOIN cart ON cart_item.cart_id = cart.id\n  JOIN customer ON cart.customer_id = customer.id\n  WHERE cart.is_deleted is false AND  $__timeFilter(cart_item.created_date) \n  GROUP BY customer.name ORDER BY sum(cart_item.quantity * product.price) DESC LIMIT 5;"
      }
     ]
    },
    {
     "title": "10 Biggest Orders",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT orders.cart_id, orders.order_uuid, orders.created_date, SUM(price*quantity) AS amount from order_table AS orders\nJOIN cart ON cart.id = orders.cart_id\nJOIN cart_item ON cart.id = cart_item.cart_id\nJOIN product ON cart_item.product_id = product.id\nWHERE  $__timeFilter(orders.created_date)\nGROUP BY (orders.order_uuid)\nORDER BY amount DESC\nLIMIT 10"
      }
     ]
    },
    {
     "title": "Amount of Orders per Minute",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT $__timeGroup(orders.created_date, '1m') AS time, count(*) AS amount FROM webshopdb.order_table AS orders\nWHERE  $__timeFilter(created_date)\nGROUP BY TIME ORDER BY time ASC"
      }
     ]
    },
    {
     "title": "Customer Name",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT cart_item.id, quantity, price, product.name, customer.name AS customer_name from cart_item\nJOIN cart ON cart.id = cart_item.cart_id\nJOIN order_table as orders ON cart.id = orders.cart_id\nJOIN product ON product.id = cart_item.product_id\nJOIN customer ON cart.customer_id = customer.id\nWHERE orders.order_uuid = \"$order_id\" AND $__timeFilter(orders.created_date)\n"
      }
     ]
    },
    {
     "title": "Order Sum",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT SUM(quantity*price) from cart_item\nJOIN cart ON cart.id = cart_item.cart_id\nJOIN order_table as orders ON cart.id = orders.cart_id\nJOIN product ON product.id = cart_item.product_id\nJOIN customer ON cart.customer_id = customer.id\nWHERE orders.order_uuid = \"$order_id\" AND $__timeFilter(orders.created_date)\n"
      }
     ]
    },
    {
     "title": "Order Details $order_id",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 4, "y": 13 },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT cart_item.id, quantity, price, product.name, customer.name AS customer_name from cart_item\nJOIN cart ON cart.id = cart_item.cart_id\nJOIN order_table as orders ON cart.id = orders.cart_id\nJOIN product ON product.id = cart_item.product_id\nJOIN customer ON cart.customer_id = customer.id\nWHERE orders.order_uuid = \"$order_id\" AND $__timeFilter(orders.created_date)\n"
      }
     ]
    },
    {
     "title": "Revenue per Minute",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT $__timeGroup(orders.created_date, '1m') AS time, sum(quantity*price) AS amount FROM webshopdb.order_table AS orders\nJOIN cart AS cart ON cart.id = orders.cart_id\nJOIN cart_item AS item ON item.cart_id = cart.id \nJOIN product ON item.product_id = product.id\nWHERE  $__timeFilter(orders.created_date)\nGROUP BY time ORDER BY time ASC\n"
      }
     ]
    },
    {
     "title": "Total Spend",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
     "targets": [
      {
       "dataset": "webshopdb",
       "rawSql": "SELECT amount FROM\n  (\n    SELECT orders.cart_id, cart.customer_id as cust_id, orders.created_date, SUM(price*quantity) AS amount from order_table AS orders\n      JOIN cart ON cart.id = orders.cart_id\n      JOIN cart_item ON cart.id = cart_item.cart_id\n      JOIN product ON cart_item.product_id = product.id\n      WHERE  $__timeFilter(orders.created_date) AND cart.customer_id = (\n\n        SELECT MAX(cart.customer_id) AS cust_id from cart_item\n          JOIN cart ON cart.id = cart_item.cart_id\n          JOIN order_table as orders ON cart.id = orders.cart_id\n          JOIN product ON product.id = cart_item.product_id\n          WHERE orders.order_uuid = \"$order_id\" AND $__timeFilter(orders.created_date)\n\n      )\n      GROUP BY (cart.customer_id)\n  ) AS t\n"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(trace_id) (count_over_time({compose_service=\"shopping-cart\"} |= `$order_id` | logfmt | __error__=`` [$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "SLOs & Error Budgets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true
  },
  {
   "title": "Front End Health Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Exceptions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(count_over_time({app=\"$app\",kind=\"exception\"} [$__range])) by (app)"
      }
     ]
    },
    {
     "title": "TTFB",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \"ttfb\" | logfmt | unwrap ttfb [$__range]) by (app)",
       "legendFormat": "TTFB"
      }
     ]
    },
    {
     "title": "FCP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" fcp=\" | logfmt | unwrap fcp [$__range]) by (app)",
       "legendFormat": "FCP"
      }
     ]
    },
    {
     "title": "CLS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \"cls\" | logfmt | unwrap cls [$__range]) by (app)",
       "legendFormat": "CLS"
      }
     ]
    },
    {
     "title": "LCP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" lcp=\" | logfmt | unwrap lcp [$__range]) by (app)",
       "legendFormat": "LCP"
      }
     ]
    },
    {
     "title": "FID",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time({kind=\"measurement\",app=\"$app\"} |= \" fid=\" | logfmt | unwrap fid [$__range]) by (app)",
       "legendFormat": "FID"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoint Heath + 4 Golden Signals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Percentage of Failing Endpoints",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (http_target)(count_over_time({traces=~\"process|root|span\"} != \"/order/\" |= \"http.status_code\" |= \"http.target\" | logfmt | http_status_code=~\"5..\" [5m])) / sum by (http_target)(count_over_time({traces=~\"process|root|span\"} != \"/order/\" |= \"http.status_code\" |= \"http.target\" | logfmt [5m]))"
      }
     ]
    },
    {
     "title": "Service Map",
     "type": "nodeGraph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {}
     ]
    },
    {
     "title": "Request Rate and Error Count of $service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[1m]))",
       "legendFormat": "Return Status {{status}}"
      },
      {
       "expr": "sum by (status) (rate(http_server_requests_seconds_count{service=~\"$service\"}[1m]))",
       "legendFormat": "Return Status {{status}}"
      },
      {
       "expr": "sum by (code) (rate(gin_requests_total{}[1m]))",
       "legendFormat": "Return Status {{code}}"
      }
     ]
    },
    {
     "title": "CPU Usage of $service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{service=~\"$service\"}[1m]))/sum(rate(node_cpu_seconds_total{job=\"node\"}[1m]))",
       "legendFormat": "{{service}}"
      },
      {
       "expr": "sum(rate(process_cpu_usage{service=~\"$service\"}[1m]))/sum(rate(node_cpu_seconds_total{job=\"node\"}[1m]))",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Error Percentage Per Service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(traces_spanmetrics_latency_count{status_code != \"STATUS_CODE_UNSET\", service=~\"$service\"}[1m]))/sum by (service_name) (rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m]))",
       "legendFormat": "{{ service_name }}"
      }
     ]
    },
    {
     "title": "Total Spans Error Percentage",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (rate(traces_spanmetrics_latency_count{status_code != \"STATUS_CODE_UNSET\"}[1m]))/sum (rate(traces_spanmetrics_latency_count{}[1m]))"
      }
     ]
    },
    {
     "title": "Status Code non-2xx Percentage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (svc) (count_over_time({traces=\"span\"} | logfmt | svc=~\"$service\" | http_status_code =~ \"...\" | http_status_code!~\"2..\" [1m])) / sum by (svc) (count_over_time({traces=\"span\"} | logfmt | svc=~\"$service\" | http_status_code=~\"...\" [1m]))",
       "legendFormat": "{{ svc }}"
      }
     ]
    },
    {
     "title": "Average Latency of $service",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(flask_http_request_duration_seconds_sum{service=~\"$service\"}[10m])) * 1 / sum(rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[10m]))",
       "legendFormat": "Average [10m]"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{service=~\"$service\"}[10m])) * 1 / sum(rate(http_server_requests_seconds_count{service=~\"$service\"}[10m]))",
       "legendFormat": "Average [10m]"
      }
     ]
    },
    {
     "title": "Endpoints of $service with Highest Latency",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(10,sum by (span_name) (rate(traces_spanmetrics_latency_sum{service=~\"$service\"}[1m]))/sum by (span_name)(rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m])))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "Latency of $service by Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum by (span_name) (rate(traces_spanmetrics_latency_sum{service=~\"$service\"}[1m]))/sum by (span_name)(rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m]))",
       "legendFormat": "{{service_name}} {{ operation }}"
      }
     ]
    },
    {
     "title": "Number of Log Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (compose_service) (count_over_time({compose_project=\"web-shop-o11y-demo\"} |= \"ERROR\" [5m]))",
       "legendFormat": "{{compose_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web Shop Logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{compose_service=~\"products|shopping-cart|squid|web-shop\"} |= \"$order_id\""
      }
     ]
    },
    {
     "title": "Span Count per 5 Minutes per Team",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (team_name) (sum_over_time(traces_spanmetrics_latency_count{}[5m]))",
       "legendFormat": "{{ team_name }} team"
      }
     ]
    }
   ]
  }
 ]
}