{
 "title": "Holistic Webshop Monitoring + Load Testing Summary",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "Test Run",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "aggregation": "value",
     "metric": "vus",
     "projectId": 3569409,
     "qtype": "metric",
     "testId": 700019,
     "testRunId": 1344928
    },
    {
     "aggregation": "rps",
     "metric": "http_reqs",
     "projectId": 3569409,
     "qtype": "metric",
     "testId": 700019,
     "testRunId": 1344928
    },
    {
     "aggregation": "0.95",
     "metric": "http_req_duration",
     "projectId": 3569409,
     "qtype": "metric",
     "testId": 700019,
     "testRunId": 1344928
    },
    {
     "aggregation": "nz_rps",
     "metric": "http_req_failed",
     "projectId": 3569409,
     "qtype": "metric",
     "testId": 700019,
     "testRunId": 1344928
    }
   ]
  },
  {
   "title": "Error Percentage Per Endpoint",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_target) (rate(traces_spanmetrics_latency_count{status_code != \"STATUS_CODE_UNSET\", service_name=~\"$service\"}[1m]))/sum by (http_target) (rate(traces_spanmetrics_latency_count{service_name=~\"$service\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPU Usage of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=~\"$service\"}[1m]))/sum(rate(node_cpu_seconds_total{job=\"node\"}[1m]))",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(rate(process_cpu_usage{service=~\"$service\"}[1m]))/sum(rate(node_cpu_seconds_total{job=\"node\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Rate and Error Count of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[1m]))",
     "legendFormat": "Return Status {{status}}"
    },
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{service=~\"$service\"}[1m]))",
     "legendFormat": "Return Status {{status}}"
    }
   ]
  },
  {
   "title": "Average Latency of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{service=~\"$service\"}[10m])) * 1 / sum(rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[10m]))",
     "legendFormat": "Average [10m]"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=~\"$service\"}[10m])) * 1 / sum(rate(http_server_requests_seconds_count{service=~\"$service\"}[10m]))",
     "legendFormat": "Average [10m]"
    }
   ]
  },
  {
   "title": "Error Percentage Per Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service_name) (rate(traces_spanmetrics_latency_count{status_code != \"STATUS_CODE_UNSET\", service_name=~\"$service\"}[1m]))/sum by (service_name) (rate(traces_spanmetrics_latency_count{service_name=~\"$service\"}[1m]))",
     "legendFormat": "{{ service_name }}"
    }
   ]
  },
  {
   "title": "Total Spans Error Percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(traces_spanmetrics_latency_count{status_code != \"STATUS_CODE_UNSET\"}[1m]))/sum (rate(traces_spanmetrics_latency_count{}[1m]))"
    }
   ]
  },
  {
   "title": "Status Code non-2xx Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (svc) (count_over_time({traces=\"span\"} | logfmt | svc=~\"$service\" | http_status_code =~ \"...\" | http_status_code!~\"2..\" [1m])) / sum by (svc) (count_over_time({traces=\"span\"} | logfmt | svc=~\"$service\" | http_status_code=~\"...\" [1m]))",
     "legendFormat": "{{ svc }}"
    }
   ]
  },
  {
   "title": "Latency of $service by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(traces_spanmetrics_latency_sum{service_name=~\"$service\"}[$__interval]))/sum by (operation)(rate(traces_spanmetrics_latency_count{service_name=~\"$service\"}[$__interval]))",
     "legendFormat": "{{service_name}} {{ operation }}"
    }
   ]
  },
  {
   "title": "Endpoints of $service with Highest Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,sum by (operation) (rate(traces_spanmetrics_latency_sum{service_name=~\"$service\"}[$__interval]))/sum by (operation)(rate(traces_spanmetrics_latency_count{service_name=~\"$service\"}[$__interval])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "5m Average Number of Web Shop Logs by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (compose_service) (count_over_time({compose_project=\"web-shop-o11y-demo\"}[5m]))",
     "legendFormat": "{{compose_service}}"
    }
   ]
  },
  {
   "title": "Web Shop Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "{compose_project=\"web-shop-o11y-demo\"}"
    }
   ]
  },
  {
   "title": "Span Count per 5 Minutes per Team",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (team_name) (sum_over_time(traces_spanmetrics_latency_count{}[5m]))",
     "legendFormat": "{{ team_name }} team"
    }
   ]
  }
 ]
}