{
 "title": "JMX Dashboard(Basic)",
 "description": "jmx exporter monitor",
 "tags": [
  "jmx",
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(jvm_info, job)" } },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{job=\"$job\", instance=\"$app$node\"}, area)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", instance=\"$app$node\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JDK",
     "type": "stat",
     "gridPos": { "h": 2, "w": 22, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "label_join(jvm_info{job=\"$job\", instance=\"$app$node\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
      }
     ]
    },
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "title": "State",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 2, "y": 3 },
     "targets": [
      {
       "expr": "up{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "State"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_Runtime_Uptime{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Uptime"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_Runtime_StartTime{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Start time"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_AvailableProcessors{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "CPU Cores"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"$job\", instance=\"$app$node\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Total RAM",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total SWAP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_TotalSwapSpaceSize{job=\"$job\", instance=\"$app$node\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Total SWAP",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Open file descriptors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Open FDs"
      }
     ]
    },
    {
     "title": "Cpu Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_ProcessCpuTime{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Process"
      },
      {
       "expr": "java_lang_Threading_CurrentThreadCpuTime{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Current Thread"
      },
      {
       "expr": "process_cpu_seconds_total{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Total Spent"
      }
     ]
    },
    {
     "title": "CPU System load average",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=\"$job\", instance=\"$app$node\"} * 100",
       "legendFormat": "CPU System load average"
      }
     ]
    },
    {
     "title": "CPU Process Load (1m avg)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(java_lang_OperatingSystem_ProcessCpuLoad{job=\"$job\", instance=\"$app$node\"}[1m]) * 100",
       "legendFormat": "CPU Process Load (1m avg)"
      }
     ]
    },
    {
     "title": "CPU System Load (1m avg)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{job=\"$job\", instance=\"$app$node\"}[1m]) * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "CPU System Load (1m avg)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 - (100 * java_lang_OperatingSystem_FreePhysicalMemorySize{job=\"$job\", instance=\"$app$node\"} / on(instance) java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"$job\", instance=\"$app$node\"})",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Memory Utilization",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SWAP Utilization",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "100 - (java_lang_OperatingSystem_FreeSwapSpaceSize{job=\"$job\", instance=\"$app$node\"} / on(instance) java_lang_OperatingSystem_TotalSwapSpaceSize{job=\"$job\", instance=\"$app$node\"} * 100)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "SWAP Utilization",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU load",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "System"
      },
      {
       "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"$job\", instance=\"$app$node\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Process",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 15, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Descriptors"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ],
   "panels": [
    {
     "title": "Physical memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Committed VM"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Virtual"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Memory Used [$memarea]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "repeat": "memarea",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=~\"$memarea\",job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area=~\"$memarea\",job=\"$job\",instance=\"$app$node\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM Memory Usage [$memarea]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "repeat": "memarea",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\", instance=\"$app$node\"} / ignoring(area) group_left java_lang_OperatingSystem_TotalPhysicalMemorySize{job=\"$job\", instance=\"$app$node\"} *100",
       "legendFormat": "System"
      },
      {
       "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\", instance=\"$app$node\"} / (jvm_memory_bytes_max{area=\"$memarea\", job=\"$job\",instance=\"$app$node\"} >=0) *100",
       "legendFormat": "JVM"
      }
     ]
    },
    {
     "title": "JVM Memory committed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_bytes_committed{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "{{area}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory JVM Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory pool [$mempool]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "repeat": "mempool",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_max{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "jvm_memory_pool_bytes_used{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_pool_bytes_committed{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "rate(jvm_memory_pool_bytes_committed{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Committed Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC count rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC Time increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    },
    {
     "title": "GC Time rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "{{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threading Threads",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "java_lang_Threading_ThreadCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "java_lang_Threading_DaemonThreadCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "java_lang_Threading_PeakThreadCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "java_lang_Threading_TotalStartedThreadCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 6 },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Started Total"
      }
     ]
    },
    {
     "title": "JVM Threading Threads increase",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(java_lang_Threading_ThreadCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "increase(java_lang_Threading_DaemonThreadCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "increase(java_lang_Threading_PeakThreadCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "increase(java_lang_Threading_TotalStartedThreadCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current increase",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 17 },
     "targets": [
      {
       "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "increase(jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "increase(jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "increase(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "increase(jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "increase(jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Started Total"
      }
     ]
    },
    {
     "title": "JVM Threading Threads rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(java_lang_Threading_ThreadCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "rate(java_lang_Threading_DaemonThreadCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "rate(java_lang_Threading_PeakThreadCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "rate(java_lang_Threading_TotalStartedThreadCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 28 },
     "targets": [
      {
       "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "rate(jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "rate(jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "rate(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "rate(jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "rate(jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Started Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Class Loading count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "java_lang_ClassLoading_LoadedClassCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "loaded"
      },
      {
       "expr": "java_lang_ClassLoading_UnloadedClassCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "currently"
      },
      {
       "expr": "jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Class Loading count increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(java_lang_ClassLoading_LoadedClassCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "loaded"
      },
      {
       "expr": "increase(java_lang_ClassLoading_UnloadedClassCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "currently"
      },
      {
       "expr": "increase(jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Class Loading count rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(java_lang_ClassLoading_LoadedClassCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "loaded"
      },
      {
       "expr": "rate(java_lang_ClassLoading_UnloadedClassCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "unloaded"
      }
     ]
    },
    {
     "title": "Classes Loaded rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "currently"
      },
      {
       "expr": "rate(jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}