{
 "title": "Order Details",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "Customers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select * from customer\nORDER BY id DESC"
    }
   ]
  },
  {
   "title": "Customers + Carts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select cart.id AS cart_id, name, customer_id from customer\njoin  cart ON customer.id = cart.customer_id\norder by customer.id DESC"
    }
   ]
  },
  {
   "title": "Cart + Cart Items",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(cart.created_date, '1m') AS time,  cart.id, customer_id, cart.is_deleted, cart.created_date, cart.updated_date, item.is_deleted as itemdeleted,  item.product_id FROM webshopdb.cart\nJOIN cart_item AS item ON item.cart_id = cart.id\nWHERE  $__timeFilter(cart.created_date) ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Orders + Cart",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(orders.created_date, '1m') AS time, cart_id FROM webshopdb.order_table AS orders\nJOIN cart AS cart ON cart.id = orders.cart_id\nWHERE  $__timeFilter(orders.created_date)\nGROUP BY time ORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Orders",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT *, $__timeGroup(orders.created_date, '1m') AS time FROM webshopdb.order_table AS orders\nWHERE  $__timeFilter(created_date)\nGROUP BY TIME ORDER BY time ASC"
    }
   ]
  }
 ]
}