{
 "title": "User and Exception Tracking",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "High Level Front End KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"web-shop-frontend\",kind=\"exception\"} [$__range])) by (app)"
    }
   ]
  },
  {
   "title": "TTFB",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"web-shop-frontend\"} |= \"ttfb\" | logfmt | unwrap ttfb [$__range]) by (app)"
    }
   ]
  },
  {
   "title": "FCP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"web-shop-frontend\"} |= \"fcp=\" | logfmt | unwrap fcp [$__range]) by (app)"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"web-shop-frontend\"} |= \"cls=\" | logfmt | unwrap cls [$__range]) by (app)"
    }
   ]
  },
  {
   "title": "LCP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"web-shop-frontend\"} |= \"lcp=\" | logfmt | unwrap lcp [$__range]) by (app)"
    }
   ]
  },
  {
   "title": "FID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time({kind=\"measurement\",app=\"web-shop-frontend\"} |= \"fid=\" | logfmt | unwrap fid [$__range]) by (app)"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Exceptions by Message",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "topk(10, count(count_over_time({kind=\"exception\", app=\"web-shop-frontend\"} | logfmt [$__range])) by (value))"
      }
     ]
    },
    {
     "title": "Top Exceptions by Browser",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "topk(10, count(count_over_time({kind=\"exception\", app=\"web-shop-frontend\"} | logfmt [$__range])) by (browser_name, browser_version))"
      }
     ]
    },
    {
     "title": "Top Exceptions by URL",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "topk(10, count(count_over_time({kind=\"exception\", app=\"web-shop-frontend\"} | logfmt [$__range])) by (page_url))"
      }
     ]
    }
   ]
  },
  {
   "title": "Top User Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Most Active Users",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "topk(10,sum by(user_id) (count_over_time({kind=~\".+\"} |= `` | logfmt [$__range])))"
      }
     ]
    },
    {
     "title": "Top 10 Users with Most Errors",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "topk(10,sum by(user_id) (count_over_time({kind=~\"exception\"} |= `` | logfmt [$__range])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Choose Timeframe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Errors per Minute",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by(user_id) (count_over_time({kind=~\"exception\"} |= `` | logfmt [1m]))",
       "legendFormat": "{{user_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Session Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Details",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "topk(100,sum by(user_id, browser_name, browser_os, browser_version, browser_mobile, app, app_environment, app_name, app_version) (count_over_time({kind=~\".+\"} |= `` | logfmt [$__range])))"
      }
     ]
    },
    {
     "title": "User Trace",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "topk(100,sum by(timestamp, page_url, page_url, kind, type, stacktrace, event_name, message, session_id) (count_over_time({kind=~\"event|exception\"} |= `` | logfmt [$__range])))"
      }
     ]
    }
   ]
  }
 ]
}