{
 "title": "Holistic Webshop Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{cluster=\"web-shop\", namespace=~\"$namespace\", workload=~\".+\"}, workload)"
    }
   }
  ]
 },
 "panels": [
  { "title": "4 Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Percentage Per Endpoint",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(traces_spanmetrics_latency_count{status_code = \"STATUS_CODE_ERROR\", service=~\"$service\"}[1m]))/sum by (span_name) (rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m]))",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "CPU Usage of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"web-shop\", namespace=\"web-shop-app\"} * on(namespace,pod)   group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"web-shop\", namespace=\"web-shop-app\", workload=~\"$service\"} ) by (workload, workload_type) ",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Request Rate and Error Count of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (status, service) (rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[5m]))",
     "legendFormat": "{{status}} - {{service}}"
    },
    {
     "expr": "sum by (status, service) (rate(http_server_requests_seconds_count{service=~\"$service\"}[1m]))",
     "legendFormat": "{{status}} - {{service}}"
    }
   ]
  },
  {
   "title": "Average Latency of $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (service) (rate(flask_http_request_duration_seconds_sum{service=~\"$service\"}[10m])) / sum by (service)(rate(flask_http_request_duration_seconds_count{service=~\"$service\"}[10m]))",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum by (service) (rate(http_server_requests_seconds_sum{service=~\"$service\"}[10m])) / sum by (service) (rate(http_server_requests_seconds_count{service=~\"$service\"}[10m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Error Percentage Per Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (rate(traces_spanmetrics_latency_count{status_code = \"STATUS_CODE_ERROR\", service=~\"$service\"}[1m]))/sum by (service) (rate(traces_spanmetrics_latency_count{status_code =~ \".+\", service=~\"$service\"}[1m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Total Spans Error Percentage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(traces_spanmetrics_latency_count{status_code != \"STATUS_CODE_UNSET\"}[1m]))/sum (rate(traces_spanmetrics_latency_count{status_code =~ \".+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Status Code non-2xx Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (svc) (count_over_time({traces=\"span\"} | logfmt | svc=~\"$service\" | http_status_code =~ \"...\" | http_status_code!~\"2..\" [1m])) / sum by (svc) (count_over_time({traces=\"span\"} | logfmt | svc=~\"$service\" | http_status_code=~\"...\" [1m]))",
     "legendFormat": "{{ svc }}"
    }
   ]
  },
  {
   "title": "Latency of $service by Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(traces_spanmetrics_latency_sum{service=~\"$service\"}[1m]))/sum by (span_name)(rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m]))",
     "legendFormat": "{{service}} {{ span_name }}"
    }
   ]
  },
  {
   "title": "Operations of $service with Highest Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,sum by (span_name) (rate(traces_spanmetrics_latency_sum{service=~\"$service\"}[1m]))/sum by (span_name)(rate(traces_spanmetrics_latency_count{service=~\"$service\"}[1m])))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "5m Average Number of Web Shop Logs by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service) (count_over_time({service=~\"$service\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Web Shop Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{service=~\"$service\"}"
    }
   ]
  },
  { "title": "Team Dev Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Commits",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 53 },
   "targets": [
    { "options": { "gitRef": "main" }, "owner": "Condla", "repository": "web-shop-o11y-demo" }
   ]
  },
  {
   "title": "Issues Opened",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "options": { "query": "is:issue is:open", "timeField": 0 }, "owner": "condla", "repository": "web-shop-o11y-demo" }
   ]
  },
  {
   "title": "Issues Closed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "options": { "query": "is:issue is:closed", "timeField": 0 }, "owner": "condla", "repository": "web-shop-o11y-demo" }
   ]
  }
 ]
}